print("#1 Mitä hyötyjä automaattisesta testauksesta on verrattuna manuaaliseen testaukseen?")
print("-automaattisessa testauksessa caset ovat aina samat. Testit suoritetaan aina samanlailla. Virheitä ei tule niin paljoa")
print("#2 Mitä haasteita testauksen automatisointi asettaa verrattuna manuaaliseen testaukseen? Pohdi näitä erityisesti kurssin sisällön kontekstissa.")
print("-Testicaset täytyy miettiä hyvin etukäteen. Aina ei ole selvää, mitä pitäisi testata, joten testicasejen teko on vaikeaa")
print("#3 Mihin tarvitaan versionhallintaa? Pohdi asiaa testausprojektin kannalta, jossa on useita rinnakkaisia testaajia tai tiimejä. Minkälaisia haasteita saatat kohdata?")
print("Koodit ovat nopeasti saatavilla. Muokkaaminen ja julkaisu on nopeaa. Haasteina esim konfliktoivat muokkaukset koodiin")
print("#4 Mitä etuja Python tarjoaa kielenä sulautetun järjestelmän testaukseen verrattuna esim. C-kieleen? Mitä haasteita?")
print("Python on dynaaminen kieli, eli devaaminen on nopeampaa. Myös Python syntaksi on ihmisystävällisempi kuin C. Haasteena on hitaampi suoritus kuin C:llä")
print("#5 Miten testiautomaatiota voisi soveltaa kurssilla tehtyihin suunnitteluesimerkkeihin?")
print("testiautomaatiota voi soveltaa esimerkkeihin kuten testiautomaatiota yleensä sovelletaan. Tehdään testicaseja, jotka pyöritetään laitteella, ja katsotaan meneekö testi läpi")